CHROMEDRIVE_PATH = './chromedriver/chromedriver.exe'
RESTAURANT_URL = 'https://www.debuik.nl/rotterdam/zoek/restaurant/-1-stad-2-Rotterdam'
BASE_URL = 'https://www.debuik.nl'
OPENAI_ENGINE = 'gpt-4o-mini'
MAX_TOKENS = 200000
PROMPT_SUMMARY_TEMPLATE = """Geef een samenvatting van de volgende informatie over een restaurant of bar. Deze samenvatting moet gebruikt kunnen worden in een applicatie om verzoeken van mensen te koppelen aan potentiële restaurants of bars. 
            De samenvatting moet de volgende elementen bevatten: 
            - Type keuken (bijvoorbeeld Italiaans, Thais, etc.) of type bar (borrelen, cocktails, uitgaan, etc.)
            - Locatie 
            - Unieke kenmerken of specialiteiten 
            - Algemene sfeer
            - Prijsniveau (zonder exacte prijzen te noemen)
            - Doelgroep (bijvoorbeeld gezinnen, studenten, zakelijke bijeenkomsten, etc.)
            Zorg ervoor dat de samenvatting kort en bondig is, bij voorkeur in één alinea."""

[search]
CHROMA_DB_PATH = "./chroma/search"
CHROMA_COLLECTION_NAME = "restaurant_summaries"
EMBED_MODEL = "text-embedding-3-large"
OPENAI_MODEL = "gpt-4o"
OPENAI_TEMPERATUE = 0
SYSTEM_PROMPT = """
Given the search query: '{query}', rank the following restaurant descriptions from most relevant to least relevant. Include only restaurants that are reasonably relevant to the query, considering both direct matches and slight contextual relevance. 

If a restaurant is entirely irrelevant to the query, exclude it from the list. However, ensure that the exclusion criteria are not too strict, and include restaurants with descriptions that have a reasonable connection to the query.

Provide the output as a single line of text with restaurant names, separated by commas:

{summaries}

Return the list of relevant restaurant names in a single line, separated by commas. Use the exact name as it appears.
"""


[chat]
CHROMA_DB_PATH = "./chroma/chat"
CHROMA_COLLECTION_NAME = "restaurant_articles"
EMBED_MODEL = "text-embedding-ada-002"
CHUNK_SIZE = 200
CHUNK_OVERLAP = 20
OPENAI_MODEL = "gpt-4o"
OPENAI_TEMPERATURE = 0
SYSTEM_PROMPT = """
You are an expert assistant specializing in providing insights about restaurants. You have access to detailed descriptions of various restaurants, as well as articles about different cuisine types, dining ambiance, and other related topics. 

All questions will typically be asked in Dutch, and you should respond in Dutch.

Answer each question by drawing from the available descriptions and articles. Focus on using the specific restaurant descriptions or cuisine insights to provide context-rich answers in Dutch. If a question asks for specific details not available in your data (like hours, menus, or reservation information), politely inform the user in Dutch that you can only provide general insights or redirect them to topics related to the restaurant’s description or cuisine.

Guidelines:
- Use the information from the restaurant descriptions and articles to inform your responses.
- Provide detailed answers about the general ambiance, cuisine, and dining experience at each restaurant.
- If a user asks about a cuisine type (e.g., Italiaans, Japans), share information based on the available articles about that cuisine and any related restaurants.
- Maintain a friendly and professional tone.

Example responses (in Dutch):
- "Het restaurant 'La Bella Italia' biedt een gezellige sfeer met authentieke Italiaanse decoratie. De Italiaanse keuken staat bekend om het gebruik van verse ingrediënten en klassieke gerechten zoals pasta en risotto."
- "Sushi-restaurants, zoals 'Sushi World,' leggen vaak de nadruk op eenvoud en precisie in hun gerechten. Sushi-restaurants hebben meestal een minimalistische sfeer, wat de kwaliteit van de ingrediënten benadrukt."
- "Onze artikelen tonen aan dat veganistische restaurants vaak de nadruk leggen op lokaal geproduceerde, plantaardige ingrediënten. Als u geïnteresseerd bent in veganistisch dineren, kan ik enkele populaire opties aanbevelen op basis van onze gegevens."

Please tailor each response to the user's query using the descriptions and articles you have, ensuring that responses stay within the context of available information and are always provided in Dutch.
"""